// Generated by CoffeeScript 2.7.0
(function() {
  // **Scope** is a base class for scoping behaviors, covering both lexical and
  // function scope.
  var BlockScope, ClassDeclarationScope, ControlFlowScope, ExecutableClassBodyScope, FunctionScope, Scope, TopLevelScope, VarScope;

  exports.Scope = Scope = class Scope {
    constructor({
        lexParent: lexParent1
      }) {
      this.lexParent = lexParent1;
      if (typeof this.lexParent === 'undefined') {
        throw new TypeError('parent key must be provided, even if null');
      }
      // The `@root` is the top-level **TopLevelScope** object for a given file. Similarly,
      // the `@varParent` is the enclosing `var` scope (either top-level, or function
      // scope). The `@lexParent` is the enclosing block scope, which may be a function scope,
      // or the top level.
      if (this.lexParent != null) {
        if (!(this.lexParent instanceof Scope)) {
          throw new TypeError(`parent must be null or Scope: ${this.lexParent}`);
        }
        this.root = this.lexParent.root;
        this.varParent = this.lexParent instanceof VarScope ? this.lexParent : this.lexParent.varParent;
        if (!(this.varParent instanceof VarScope)) {
          throw new TypeError(`an enclosing var scope key must be provided: ${this.varParent}/${this.lexParent}`);
        }
      } else {
        if (!(this instanceof TopLevelScope)) {
          throw new TypeError(`if parent is null, this must be a TopLevelScope: ${this}`);
        }
        this.root = this;
        this.varParent = null;
      }
      if (!(this.root instanceof TopLevelScope)) {
        throw new TypeError(`a top-level root key must be provided: ${this.root}/${this.lexParent}`);
      }
    }

    // This method returns the current function scope, which may contain any number of
    // internal lexical/block scopes. This method always succeeds, unlike
    // `VarScope#tryAsFunctionScope()`.
    asVarScope() {
      if (this instanceof VarScope) {
        return this;
      } else {
        return this.varParent;
      }
    }

  };

  // The **VarScope** class regulates lexical scoping within CoffeeScript. As you
  // generate code, you create a tree of scopes in the same shape as the nested
  // function bodies. Each scope knows about the variables declared within it,
  // and has a reference to its parent enclosing scope. In this way, we know which
  // variables are new and need to be declared with `var`, and which are shared
  // with external scopes.
  exports.VarScope = VarScope = class VarScope extends Scope {
    constructor({lexParent}) {
      super({lexParent});
      this.variables = new Map();
      this.comments = {};
    }

    // Return whether a variable was declared by the given name in exactly this scope,
    // without checking any parents.
    hasName(name) {
      return this.variables.has(name);
    }

    // Retrieves the `spec` data stored from a prior `@internNew(name, spec)` invocation, or
    // `undefined`.
    getSpec(name) {
      return this.variables.get(name);
    }

    // Determine whether a proposed new specification for the name binding should overwrite
    // the previous value.
    overwriteSpec(name, newSpec) {
      var prevSpec;
      prevSpec = this.getSpec(name);
      this.variables.set(name, newSpec);
      return;
      // If the types are the same, we have nothing to do.
      if (prevSpec.type === newSpec.type) {
        return;
      }
      // If a variable was previously referenced within the body of a scope, but it was registered via `utilities` as e.g. a polyfill with special meaning (like `indexOf`), then overwrite the specification.
      if (prevSpec.type === 'var' && newSpec.type === 'assigned') {
        this.variables.set(name, newSpec);
        return;
      }
      // Otherwise, we do not accept the modification (this should never occur).
      throw new Error(`decl with type '${newSpec}' named '${name}' was already reserved with type '${prevSpec}'`);
    }

    // Internal method to add a new variable to the scope, erroring if already seen (this
    // should never happen).
    internNew(name, spec) {
      if ((this.varParent != null) && this.delegateToParent) {
        return this.varParent.internNew(name, spec);
      }
      if (this.variables.has(name)) {
        throw new Error(`already interned existing name '${name}'`);
      }
      this.variables.set(name, spec);
      return this;
    }

    // Just check to see if a variable has already been declared, without reserving,
    // walks up to the root scope.
    check(name) {
      var ref;
      return this.hasName(name) || ((ref = this.varParent) != null ? ref.check(name) : void 0);
    }

    // Like `check()`, but returns the registered specification. This can be used to
    // introspect based upon the type of declaration assigned to the given name. For
    // example, imported symbols from the top-level scope cannot be assigned to at
    // runtime, so we also verify this at compile-time.
    checkSpec(name) {
      var ref, ref1;
      return (ref = this.getSpec(name)) != null ? ref : (ref1 = this.varParent) != null ? ref1.checkSpec(name) : void 0;
    }

    // Adds a new variable or overrides an existing one.
    add(name, spec, immediate) {
      if ((this.varParent != null) && this.shared && !immediate) {
        return this.varParent.add(name, spec, immediate);
      }
      if (this.hasName(name)) {
        return this.overwriteSpec(name, spec);
      }
      return this.internNew(name, spec);
    }

    // Look up a variable name in lexical scope, and declare it if it does not
    // already exist.

      // **TODO: "find" is an extremely misleading name, as is "check".** Neither of them
    // indicate whether they mutate the scope data structure, nor even whether their
    // search is recursive or single-level.
    find(name, type = 'var') {
      if (this.check(name)) {
        return true;
      }
      this.add(name, {type});
      return false;
    }

    // Reserve a variable name as originating from a function parameter, or seeded from the
    // `locals` argument at top level. No `var` required for internal references.
    parameter(name) {
      var ref;
      if (this.shared && ((ref = this.varParent) != null ? ref.check(name) : void 0)) {
        return;
      }
      return this.add(name, {
        type: 'param'
      });
    }

    // Generate a temporary variable name at the given index.
    static temporary(name, index, single = false) {
      var diff, endCode, letter, newCode, num, startCode;
      if (typeof single !== 'boolean') {
        throw new TypeError(`invalid single arg: ${single}`);
      }
      if (!single) {
        return `${name}${index || ''}`;
      }
      startCode = name.charCodeAt(0);
      endCode = 'z'.charCodeAt(0);
      diff = endCode - startCode;
      newCode = startCode + index % (diff + 1);
      letter = String.fromCharCode(newCode);
      num = Math.floor(index / (diff + 1));
      return `${letter}${num || ''}`;
    }

    // If we need to store an intermediate result, find an available name for a
    // compiler-generated variable. `_var`, `_var2`, and so on...
    freeVariable(name, {single, reserve} = {}) {
      var index, temp;
      if (reserve == null) {
        reserve = true;
      }
      index = 0;
      while (true) {
        temp = this.constructor.temporary(name, index, single);
        if (!(this.check(temp) || this.root.referencedVars.has(temp))) {
          break;
        }
        index++;
      }
      if (reserve) {
        this.add(temp, {
          type: 'var'
        }, true);
      }
      return temp;
    }

    // Ensure that an assignment is made at the top of this scope
    // (or at the top-level scope, if requested).
    assign(name, value) {
      this.add(name, {
        type: 'assigned',
        value
      }, true);
      return this.hasAssignments = true;
    }

    // Does this scope have any declared variables?

      // Note that this is computed dynamically, *unlike* `@hasAssignments`, because a `'var'`
    // can be overwritten later with `.overwriteSpec()`!
    hasDeclarations() {
      return !this.declaredVariables().next().done;
    }

    // Return the list of variables first declared in this scope.
    * declaredVariables() {
      var name, results, spec, x;
      results = [];
      for (x of this.variables) {
        [name, spec] = x;
        if (spec.type === 'var') {
          results.push((yield name));
        }
      }
      return results;
    }

    // Return the list of assignments that are supposed to be made at the top
    // of this scope.
    assignedVariables() {
      var name, results, type, value, x;
      results = [];
      for (x of this.variables) {
        [name, {type, value}] = x;
        if (type === 'assigned') {
          results.push(`${name} = ${value}`);
        }
      }
      return results;
    }

    // Try downcasting this scope to a function scope. This will fail at the top level,
    // for example.
    tryAsFunctionScope() {
      if (this instanceof FunctionScope) {
        return this;
      } else {
        return null;
      }
    }

  };

  // A function scope is much more common than the top-level scope, and has a few extras,
  // including (often) a method name, and a provided `arguments` parameter.
  exports.FunctionScope = FunctionScope = class FunctionScope extends VarScope {
    // Initialize a scope with its parent, for lookups up the chain,
    // as well as a reference to the **Block** node it belongs to, which is
    // where it should declare its variables, a reference to the function that
    // it belongs to, and a list of variables referenced in the source code
    // and therefore should be avoided when generating variables. Also track comments
    // that should be output as part of variable declarations.
    constructor({
        parent,
        method: method1
      }) {
      if (parent == null) {
        throw new TypeError('function scope is not top-level and must have parent');
      }
      super({
        lexParent: parent
      });
      this.method = method1;
      this.variables.set('arguments', {
        type: 'arguments'
      });
    }

    // When `super` is called, we need to find the name of the current method we're
    // in, so that we know how to invoke the same method of the parent class. This
    // can get complicated if super is being called from an inner function.
    // `namedMethod` will walk up the scope tree until it either finds the first
    // function object that has a name filled in, or bottoms out.
    namedMethod() {
      var ref;
      if (this.method.name) {
        return this.method;
      } else {
        return (ref = this.varParent.tryAsFunctionScope()) != null ? ref.namedMethod() : void 0;
      }
    }

  };

  // This is a variant of function scope that appears when adding statements to be
  // executed within class bodies. It is compiled to a regular IIFE.
  exports.ExecutableClassBodyScope = ExecutableClassBodyScope = class ExecutableClassBodyScope extends FunctionScope {
    constructor({
        parent,
        method,
        class: _class
      }) {
      super({parent, method});
      this.class = _class;
    }

  };

  // A scope without any IIFE wrapping, suitable for declaring imports and exports.
  exports.TopLevelScope = TopLevelScope = class TopLevelScope extends VarScope {
    constructor({
        referencedVars,
        block: block1
      }) {
      super({
        lexParent: null
      });
      this.block = block1;
      this.referencedVars = new Set(referencedVars);
      this.utilities = new Map();
      // In addition to tracking var-scope symbols, we also now track which symbols have
      // been imported and exported. This allows us to identify situations which would
      // otherwise produce a runtime error, as well as avoid confusion between var and
      // imported declarations.
      this.importedSymbols = new Set();
      this.exportedSymbols = new Set();
      this.defaultExportWasSet = false;
    }

    static addNew(set, element) {
      if (set.has(element)) {
        return true;
      } else {
        set.add(element);
        return false;
      }
    }

    // These methods add a new symbol to the import or export tables.
    tryNewImport(name) {
      return !this.find(name, 'import') && !this.constructor.addNew(this.importedSymbols, name);
    }

    tryNewExport(name) {
      return !this.constructor.addNew(this.exportedSymbols, name);
    }

    tryDefaultExport() {
      if (this.defaultExportWasSet) {
        return false;
      } else {
        return this.defaultExportWasSet = true;
      }
    }

    // Mark given local variables in the root scope as parameters so they don’t
    // end up being declared on the root block.
    static withLocals({block, referencedVars, locals}) {
      var i, len, name, ref, ret;
      ret = new this({block, referencedVars});
      ref = locals != null ? locals : [];
      for (i = 0, len = ref.length; i < len; i++) {
        name = ref[i];
        ret.parameter(name);
      }
      return ret;
    }

  };

  // **ControlFlowScope** is recorded separately from **VarScope** instances, and will perform
  // the task of `const` and `let` allocation, while also making it easier for `import`
  // and `export` declarations to clearly identify when they're not at the top level
  // (e.g. within an `if` block).
  exports.ControlFlowScope = ControlFlowScope = class ControlFlowScope extends Scope {
    constructor({
        parent,
        controlFlowConstruct: controlFlowConstruct1
      }) {
      super({
        lexParent: parent
      });
      this.controlFlowConstruct = controlFlowConstruct1;
    }

  };

  // **BlockScope** is a control flow scope associated to a specific **Block**. Some
  // constructs like `switch` expressions have scoping that doesn't strictly conform to
  // a block.
  exports.BlockScope = BlockScope = class BlockScope extends ControlFlowScope {
    constructor({
        parent,
        controlFlowConstruct,
        block: block1
      }) {
      super({parent, controlFlowConstruct});
      this.block = block1;
    }

  };

  // Class declarations are special (both in CoffeeScript and its compile output), so
  // class scoping is given its own class.
  exports.ClassDeclarationScope = ClassDeclarationScope = class ClassDeclarationScope extends Scope {
    constructor({
        parent,
        class: _class
      }) {
      super({
        lexParent: parent
      });
      this.class = _class;
    }

  };

}).call(this);
